# Generated by Django 3.2 on 2021-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='pick_up_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
