# Generated by Django 3.2 on 2021-05-25 10:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_transport_pick_up_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='air_conditioner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='automat_gearbox',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='baggage_places',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='transport',
            name='passenger_places',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='pay_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='transport.pay_method'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rent_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='transport.transport'),
        ),
    ]
