# Generated by Django 3.2 on 2021-05-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20210525_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='air_conditioner',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='automat_gearbox',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
